#if !canImport(ObjectiveC)
import XCTest

extension kappserverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__kappserverTests = [
        ("testNothing", testNothing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(kappserverTests.__allTests__kappserverTests),
    ]
}
#endif
