#if !canImport(ObjectiveC)
import XCTest

extension ComputeCoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComputeCoderTests = [
        ("testBasicExecFile", testBasicExecFile),
        ("testClose", testClose),
        ("testDataFrameParser", testDataFrameParser),
        ("testErrorMalformed", testErrorMalformed),
        ("testErrorSuccess", testErrorSuccess),
        ("testExecuteFile", testExecuteFile),
        ("testExecuteScript", testExecuteScript),
        ("testGetVariable", testGetVariable),
        ("testHelp", testHelp),
        ("testHelpMalformed", testHelpMalformed),
        ("testHelpSuccess", testHelpSuccess),
        ("testListVariables", testListVariables),
        ("testOpen", testOpen),
        ("testOpenFailure", testOpenFailure),
        ("testOpenMalformed", testOpenMalformed),
        ("testOpenSuccess", testOpenSuccess),
        ("testResults", testResults),
        ("testSaveEnvironment", testSaveEnvironment),
        ("testShowOutput", testShowOutput),
        ("testToggleWatch", testToggleWatch),
        ("testVariableDelta", testVariableDelta),
        ("testVariableUpdate", testVariableUpdate),
    ]
}

extension CodingTests {
       static let __allTests__CodingTests = [
           ("testPreviewUpdated", testPreviewUpdated),
       ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ComputeCoderTests.__allTests__ComputeCoderTests),
        testCase(CodingTests.__allTests__CodingTests),
    ]
}
#endif
