#if !canImport(ObjectiveC)
import XCTest

extension Rc2DAOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Rc2DAOTests = [
        ("testFiles", testFiles),
        ("testImages", testImages),
        ("testSessionRecord", testSessionRecord),
        ("testUserMethods", testUserMethods),
        ("testWorkspaceMethods", testWorkspaceMethods),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Rc2DAOTests.__allTests__Rc2DAOTests),
    ]
}
#endif
